#!/usr/bin/env bash

set -e

# Script version
VERSION=0.0.1
# Script filename
FILENAME=$(basename $0)

# CLI arguments
#
# Start date range
START_DATE=${1:-$(date --date='-1 month' -I)}
# End date range
END_DATE=${2:-$(date --date='+1 month' -I)}
# Output report
OUTPUT=${3:-"report.html"}
# Starting point
STARTING_POINT=${4:-"/var/log/nginx/access.log*"}

# Environment variables
#
# goaccess configuration
CONF=${CONF:-"/etc/goaccess/goaccess.conf"}
#Target domain and subdomains only
GREP_FILTER=${GREP_FILTER:-"theobori.cafe"}

# Help display function
print_help() {
    cat <<EOF
${FILENAME}
Version ${VERSION}

Arguments
${FILENAME} <start_date> <end_date> <output path> <file(s)/dir>

The following environment variables are overridable:
- GREP_FILTER
- CONF

Usage example:

CONF="custom.conf" ${FILENAME} \\
    "$(date --date='-1 month' -I)" \\
    "$(date --date='+1 month' -I)" \\
    "report.html" \\
    "web_server_logs/*.log"
EOF
} 

report() {
    local files=$(find ${STARTING_POINT} -maxdepth 1 -newermt "${START_DATE}" ! -newermt "${END_DATE}")

    if [[ -z ${files} ]]
    then
        echo "Missing files to process !"
        exit 1
    fi

    zcat -f ${files} \
        | grep ${GREP_FILTER} \
        | goaccess -o ${OUTPUT} --log-format=COMBINED -p ${CONF}
}

main() {
    if [[ ${#@} -lt 3 ]]
    then
        print_help
        exit 1
    fi
    
    report
}

main ${@}
